version: '3'

services:
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 8000:80
    volumes:
      # nginx settings
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      # gikenweb pages
      - ./static:/var/www/html
    depends_on:
      - dog_app
  dog_app:
    build:
      context: ./fosterParentDog
    # goアプリ側(realize)で処理するため不要
    # command: go run server.go
    volumes:
      - ./fosterParentDog:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:9.2-alpine
    volumes:
      # 初期データ投入用
      - ./config/postgres/init.d:/docker-entrypoint-initdb.d
      # データ保持用
      - ./config/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  pgadmin:
    image: dpage/pgadmin4:4.29
    ports:
      - 8001:80
    volumes:
      - ./config/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
