settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: fosterParentDog
    path: .
    commands:
      # realize startで実行するコマンド
      install:
        status: true
        method: go build -o foster-parent-dog-app server.go
      # installで作成したバイナリファイルを監視/ホットリロードする
      run:
        status: true
        method: ./foster-parent-dog-app
      #build:
      #  status: true
      #  method: go build -o foster-parent-dog-app server.go
    watcher:
      # 監視ファイルを指定する
      extensions:
        - go
        - env
        - vue
        - js
        - mod
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
        - .history
#          使用しない
        # Goland_リモートデバッグ用設定（接続はできるが止まらない）
#      scripts:
#        - type: before
#          command: pkill foster-parent-dog-app
#          output: true
          # 初回起動、またホットリロードの度に実行する。
        #          [ 15:43:40 ][ FOSTERPARENTDOG ]: Install started
        #          [ 15:43:43 ][ FOSTERPARENTDOG ]: Install completed in 3.226 s
        #          [ 15:43:43 ][ FOSTERPARENTDOG ]: Command "pwd" ←ここがcommand
#        - type: after
#          command: dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./foster-parent-dog-app
#          output: true